ROSETTA: $ROSETTA
ROSETTA_BIN: $ROSETTA_BIN
WORK_NAME: 6m0j
WT_NAME: 6m0j
WORK_DIR: /share/home/cheny/Projects/stable_final/6m0j
INPUT_DIR: /share/home/cheny/Projects/stable_final/6m0j/data
OUTPUT_DIR: /share/home/cheny/Projects/stable_final/6m0j/output
OLD_RUN_DIR: /share/home/cheny/Projects/stable_final
RUN_DIR: /share/home/cheny/Projects/stable_final/6m0j/snakemake/
UTILS_PATH: /share/home/cheny/Projects/stable_final/6m0j/utils
DATA_PATH: /share/home/cheny/Projects/stable_final/6m0j/output/data
RUN_FILE: /share/home/cheny/Projects/stable_final/6m0j/output/utils
PYTHON_PATH: /share/home/cheny/.conda/envs/pyrosetta/bin/python
ALL_CHAINS: AE
TARGET_CHAIN: E
ANOTHER_CHAIN: A
DISTANCE: 7
PDB_START: 333
PDB_END: 526
THREADS: 256
NODE: 8
NTASKS: 32
NUM: 5000
PM_NUM: 1
PDB_TOTAL: 793
TARGET_METHOD: residue
TARGET_CHARGE: positive
TOP_PM_NUM: 10
IN_SITE: 498R
