ROSETTA: /share/app/rosetta/3.14/rosetta.source.release-314
ROSETTA_BIN: /share/app/rosetta/3.14/rosetta.source.release-314/main/source/bin
WORK_NAME: 109l
WT_NAME: 109l
WORK_DIR: ./109l
INPUT_DIR: ./109l/data
OUTPUT_DIR: ./109l/output
RUN_DIR: /share/home/cheny/Projects/git/ProteinOpt
UTILS_PATH: ./109l/utils
DATA_PATH: ./109l/output/data
RUN_FILE: ./109l/output/utils
PYTHON_PATH: /share/home/cheny/.conda/envs/pyrosetta/bin/python3.9
ALL_CHAINS: A
TARGET_CHAIN: A
ANOTHER_CHAIN: ''
DISTANCE: 7
PDB_START: 1
PDB_END: 162
THREADS: 60
NODE: 2
NTASKS: 30
NUM: 50
PM_NUM: 1
PDB_TOTAL: 164
TARGET_METHOD: residue
TARGET_CHARGE: positive
TOP_PM_NUM: 10
IN_SITE: 43A
